# ---
- name: Install Docker
  hosts: testUbuntu
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Install vs offisial script
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker # Скрипт не будет запускаться, если папка уже есть
